/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Statistics {
  active_connections: number;
  registered_domains: number;
  avg_bytes_ingress: number;
  avg_bytes_egress: number;
  [k: string]: unknown;
}
